version: 1.0.{build}

before_build:
- ps: >-
    
    Write-Host "    Downloading pexports..."
    
    curl -o "pexports.tar.xz" "https://github.com/callofduty4x/CoD4x_Server/raw/master/tools/pexports-0.47-mingw32-bin.tar.xz"
    
    Write-Host "    Installing pexports..."

    7z x pexports.tar.xz | Out-Null

    7z x pexports.tar | Out-Null

    Write-Host "Setting up NASM:"
    
    Write-Host "    Downloading NASM..."
    
    #curl -o nasminst.exe https://www.nasm.us/pub/nasm/releasebuilds/2.14rc15/win32/nasm-2.14rc15-installer-x86.exe

    #nasm's main site down...

    curl -o nasminst.exe https://github.com/callofduty4x/CoD4x_Server/blob/master/tools/nasm-2.14rc0-installer-x86.exe?raw=true
    
    Write-Host "    Installing NASM..."
    
    .\nasminst.exe /S

    $env:path="C:\Program Files (x86)\nasm;$($env:path)"

    nasm -v
    
    Write-Host "Setting up environment variables."
    
    ls C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32
    
    [Environment]::SetEnvironmentVariable("PATH",  "C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;$pwd\bin;C:\Program Files (x86)\nasm;$($env:path)")

build_script:
- ps: >-
    echo "Building server code:"
    
    mingw32-make.exe DEBUG=true
    
    7z a cod4x18_dedrun_DEBUG.zip bin\cod4x18_dedrun.exe
    
    mingw32-make.exe
    
    mingw32-make.exe plugins

    Write-Host "Done."
test_script:
- ps: ./bin/cod4x18_dedrun.exe
branches:
  only:
    - master    # Ignore all other branches.
    - cmake
artifacts: 
  - path: bin\cod4x18_dedrun.exe
    name: cod4exe
    
  - path: cod4x18_dedrun_DEBUG.zip
    name: cod4exe_dbg

  - path: plugins\**\*.dll
    name: plugins
deploy:
- provider: GitHub
  auth_token:
    secure: Y+KLKu288egStZwCpdn5g0Vo3+qGefHqALRRR7wKfV1DD5CPSHJVtCUaECQT5GJx
  artifact: cod4exe, cod4exe_dbg, plugins
  draft: false
  prerelease: false
  force_update: true
  tag: $(APPVEYOR_REPO_TAG_NAME)
  on:
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
